create table if not exists responses (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),

    participant_id text,
    started_at text,
    finished_at text,
    consentimento text,

    perfil_01 text,
    perfil_02 text,
    perfil_03 text,
    perfil_04 text,
    perfil_05 text,

    scenario_id text,
    scenario_label text,

    hum_decision_initial text,
    hum_confidence_initial integer,
    hum_main_factor text,
    hum_risk_perceived integer,

    ai_signal text,
    ai_confidence text,
    ai_summary text,
    ai_factors text,
    market_context text,

    ia_agreement integer,
    ia_trust integer,
    ia_explainability integer,

    hyb_change text,
    hyb_decision_final text,
    hyb_influence integer,
    hyb_confidence_final integer,

    decision_changed integer,
    confidence_change integer,

    final_01_difficulty integer,
    final_02_general_confidence integer,
    final_03_ai_usefulness integer,
    final_04_ai_revision_frequency text,
    final_05_perceived_correctness text,
    final_06_willingness_to_use_ai integer
);
